trigger:
  - master

variables:
  system.debug: true

jobs:
  - job: macOS
    pool:
      vmImage: "macOS-latest"
    steps:
      - checkout: self
        submodules: recursive
      - task: Cache@2
        displayName: Cache vcpkg
        inputs:
          key: $(Build.SourcesDirectory)/vcpkg-ports.txt | $(Build.SourcesDirectory)/.git/modules/vcpkg/HEAD | "$(Agent.OS)"
          path: "$(Build.SourcesDirectory)/vcpkg"
      - task: lucappa.cmake-ninja-vcpkg-tasks.d855c326-b1c0-4d6f-b1c7-440ade6835fb.run-vcpkg@0
        inputs:
          vcpkgArguments: "@$(Build.SourcesDirectory)/vcpkg-ports.txt --triplet x64-osx"
          vcpkgDirectory: "$(Build.SourcesDirectory)/vcpkg"
      - task: lucappa.cmake-ninja-vcpkg-tasks.f2b1ec7d-bc54-4cc8-b9ed-1bc7f37c9dc6.run-cmake@0
        inputs:
          useVcpkgToolchainFile: true

  - job: Windows
    pool:
      vmImage: "windows-latest"
    steps:
      - checkout: self
        submodules: recursive
      - task: Cache@2
        displayName: Cache vcpkg
        inputs:
          key: $(Build.SourcesDirectory)/vcpkg-ports.txt | $(Build.SourcesDirectory)/.git/modules/vcpkg/HEAD | "$(Agent.OS)"
          path: "$(Build.SourcesDirectory)/vcpkg"
      - task: lucappa.cmake-ninja-vcpkg-tasks.d855c326-b1c0-4d6f-b1c7-440ade6835fb.run-vcpkg@0
        inputs:
          vcpkgArguments: "@$(Build.SourcesDirectory)/vcpkg-ports.txt --triplet x64-windows"
          vcpkgDirectory: "$(Build.SourcesDirectory)/vcpkg"
      - task: lucappa.cmake-ninja-vcpkg-tasks.f2b1ec7d-bc54-4cc8-b9ed-1bc7f37c9dc6.run-cmake@0
        inputs:
          useVcpkgToolchainFile: true

  - job: Linux
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - checkout: self
        submodules: recursive
      - task: Cache@2
        displayName: Cache vcpkg
        inputs:
          key: $(Build.SourcesDirectory)/vcpkg-ports.txt | $(Build.SourcesDirectory)/.git/modules/vcpkg/HEAD | "$(Agent.OS)"
          path: "$(Build.SourcesDirectory)/vcpkg"
      - task: lucappa.cmake-ninja-vcpkg-tasks.d855c326-b1c0-4d6f-b1c7-440ade6835fb.run-vcpkg@0
        inputs:
          vcpkgArguments: "@$(Build.SourcesDirectory)/vcpkg-ports.txt --triplet x64-linux"
          vcpkgDirectory: "$(Build.SourcesDirectory)/vcpkg"
      - task: lucappa.cmake-ninja-vcpkg-tasks.f2b1ec7d-bc54-4cc8-b9ed-1bc7f37c9dc6.run-cmake@0
        inputs:
          useVcpkgToolchainFile: true
